name: inqua26
channels:
  - conda-forge
dependencies:
  - python ~=3.11
  - bmi-geotiff
  - bmi-topography
  - bmipy
  - imageio
  - ipykernel
  - jupyter
  - landlab >=2.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - pymt >=1.3
  - pymt_child
  - pymt_hydrotrend
  - pytest
  - rasterio
  - scipy
  - setuptools==81.0.0
  - terrainbento
  - tqdm
  - nox
  - pip:
    - git+https://github.com/csdms/bmi-example-python.git
